# Build stage
FROM node:24-bullseye-slim AS build-stage

WORKDIR /usr/src/app

ENV CI=true
COPY package*.json ./
RUN npm ci

COPY . .
ARG VITE_BACKEND_URL="http://localhost:3000"
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
RUN ["npm", "run", "test"]
RUN ["npm", "run", "build"]

# Production stage
FROM nginx:1.29-alpine

COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80